apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vm6cf01e2-go
  janus-idp.io/tekton: vm6cf01e2-go
  backstage.io/kubernetes-id: vm6cf01e2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vm6cf01e2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
